### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by zyqf** [spance/AirGoo#29]
$ node server.js
30 May 08:12:31 - * - AirGoo-Server stopped.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
zyqf@google:~/workspace $ node server.js
30 May 08:16:47 - * - AirGoo-Server stopped.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by spance** [comment]
端口被占用了，换个端口或者检查清理谁占了端口。

**Comment by zyqf** [comment]
多谢!!!!!

2015-05-30 23:03 GMT+08:00 Spance <notifications@github.com>:
